/**
 * 侧栏与动态子路由的写死菜单树（联调阶段使用）。
 * 登录后按当前用户拉菜单尚未接入时，仍保证首页、系统页与演示项可点可测。
 * 结构应与 peach-common-service 中 init_data.sql 的 cmn_menu 层级一致（route_path / icon 对齐）。
 */

import type { MenuMgmtVO } from '../models/menuMgmt'

export const STATIC_SIDEBAR_MENU_TREE: MenuMgmtVO[] = [
  {
    id: 'st-home-root',
    menuCode: 'NAV_HOME',
    menuName: '首页',
    menuType: 'CATALOG',
    routePath: '/home',
    icon: 'House',
    orderNo: 5,
    valid: 1,
    children: [
      {
        id: 'st-1',
        menuCode: 'HOME',
        menuName: '工作台',
        menuType: 'MENU',
        routePath: '/dashboard',
        icon: 'House',
        orderNo: 10,
        valid: 1,
      },
    ],
  },
  {
    id: 'st-ops-root',
    menuCode: 'NAV_OPS',
    menuName: '运营',
    menuType: 'CATALOG',
    routePath: '/ops',
    icon: 'Operation',
    orderNo: 10,
    valid: 1,
    children: [
      {
        id: 'st-sys',
        menuCode: 'SYS_MGMT',
        menuName: '系统管理',
        menuType: 'CATALOG',
        routePath: '/system',
        icon: 'Setting',
        orderNo: 10,
        valid: 1,
        children: [
          {
            id: 'st-2',
            menuCode: 'SYS_USER',
            menuName: '用户管理',
            menuType: 'MENU',
            routePath: '/system/user',
            icon: 'User',
            orderNo: 11,
            valid: 1,
          },
          {
            id: 'st-3',
            menuCode: 'SYS_ROLE',
            menuName: '角色管理',
            menuType: 'MENU',
            routePath: '/system/role',
            icon: 'Lock',
            orderNo: 12,
            valid: 1,
          },
          {
            id: 'st-dict',
            menuCode: 'SYS_DICT',
            menuName: '码表配置',
            menuType: 'MENU',
            routePath: '/system/dict',
            icon: 'Collection',
            orderNo: 13,
            valid: 1,
          },
          {
            id: 'st-scheduler',
            menuCode: 'SYS_SCHEDULER',
            menuName: '定时任务管理',
            menuType: 'MENU',
            routePath: '/system/scheduler',
            icon: 'Clock',
            orderNo: 15,
            valid: 1,
          },
          {
            id: 'st-4',
            menuCode: 'SYS_MENU_MGMT',
            menuName: '菜单管理',
            menuType: 'MENU',
            routePath: '/system/menu',
            icon: 'Menu',
            orderNo: 14,
            valid: 1,
          },
        ],
      },
      {
        id: 'st-demo-root',
        menuCode: 'OPS_DEMO_LINKS',
        menuName: '演示与外链',
        menuType: 'CATALOG',
        routePath: '/ops/demo',
        icon: 'Link',
        orderNo: 20,
        valid: 1,
        children: [
          {
            id: 'st-demo-swagger',
            menuCode: 'DEMO_SWAGGER',
            menuName: '演示Swagger',
            menuType: 'MENU',
            routePath: 'frame://http://127.0.0.1:8090/swagger-ui.html',
            icon: 'Document',
            orderNo: 41,
            valid: 1,
          },
          {
            id: 'st-demo-ext',
            menuCode: 'DEMO_OPEN_EXT',
            menuName: '新窗口外站',
            menuType: 'MENU',
            routePath: 'openwindow://http://127.0.0.1:8090/index.html',
            icon: 'Link',
            orderNo: 42,
            valid: 1,
          },
          {
            id: 'st-demo-int',
            menuCode: 'DEMO_OPEN_INT',
            menuName: '新窗口站内',
            menuType: 'MENU',
            routePath: 'openwindow://system/menu',
            icon: 'Share',
            orderNo: 43,
            valid: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'st-report-root',
    menuCode: 'NAV_REPORT',
    menuName: '报表',
    menuType: 'CATALOG',
    routePath: '/report',
    icon: 'Histogram',
    orderNo: 15,
    valid: 1,
    children: [
      {
        id: 'st-report-overview',
        menuCode: 'REPORT_OVERVIEW',
        menuName: '报表总览',
        menuType: 'MENU',
        routePath: '/report/overview',
        icon: 'Histogram',
        orderNo: 10,
        valid: 1,
      },
    ],
  },
]
